export const env = {
  DB_CONNECT_STRING: process.env.DB_CONNECT_STRING || "",
  MQTT_HOST: process.env.MQTT_HOST,
  MQTT_PORT: process.env.MQTT_PORT || 1883,
  MQTT_USERNAME: process.env.MQTT_USERNAME || "default_user",
  MQTT_PWD: process.env.MQTT_PWD || "default_pwd",
  SOCKET_PORT: process.env.SOCKET_PORT || 3000,
  MQTT_PREFIX_TOPIC: process.env.MQTT_PREFIX_TOPIC,
  ZONE_SECRET: process.env.ZONE_SECRET,
  BASIC_AUTH_USERNAME: process.env.BASIC_AUTH_USERNAME,
  BASIC_AUTH_PASSWORD: process.env.BASIC_AUTH_PASSWORD,
  INIT: process.env.INIT || 0,
  BOT_TOKEN: process.env.BOT_TOKEN || "",
  BOT_ALLOW_USER: process.env.BOT_ALLOW_USER || 0,
  NODE_ENV: process.env.NODE_ENV || "production",
  SECRET_KEY_INTERNAL: process.env.SECRET_KEY_INTERNAL || "pl12hs228as",
  KEY_SIGN: process.env.KEY_SIGN || "",
  SECRET_KEY_SIGN: process.env.SECRET_KEY_SIGN || "",
};
